#!/bin/sh

. /root/test-config

if [ ! -e /dev/vdb ]; then
    ln -s $PRI_TST_DEV /dev/vdb
    ln -s $SM_SCR_DEV /dev/vdc
    ln -s $SM_TST_DEV /dev/vdd
    [ -n "$LG_SCR_DEV" ] && ln -s $LG_SCR_DEV /dev/vde
    [ -n "$LG_TST_DEV" ] && ln -s $LG_TST_DEV /dev/vdf
fi

mkdir -p /vdb /vdc /vdd /vde /vdf

if test -z "$FS"
then
   FS="$FSTESTTYP"
fi

if test -z "$FS"
then
   FS=ext4
fi

if ! grep -q /dev/vdb /etc/fstab
then
   cat >> /etc/fstab << EOF
/dev/vdb	/vdb	$FS	defaults 0 2
/dev/vdc	/vdc	$FS	defaults 0 2
/dev/vdd	/vdd	$FS	defaults 0 2
/dev/vde	/vde	$FS	defaults 0 2
/dev/vdf	/vdf	$FS	defaults 0 2
EOF
fi

exit 0
