#!/bin/bash
#
# This script fetches the self-signed SSL cert from the user's configured
# GS_BUCKET before lighttpd is allowed to start.
. /usr/local/lib/gce-funcs
gsutil cp gs://$GS_BUCKET/gce-xfstests-server.pem /etc/lighttpd/server.pem
/usr/local/lib/gce-logger "fetching cert completed, gsutil returned $?"

if gsutil -q stat gs://$GS_BUCKET/gce_xfstests.config &> /dev/null ; then
  gsutil cp gs://$GS_BUCKET/gce_xfstests.config "$GCE_CONFIG_FILE"
  /usr/local/lib/gce-logger "fetching config completed, gsutil returned $?"
fi

chmod 0400 /etc/lighttpd/server.pem

# Set up the necessary configuration files for the gce-xfstests script
# installed in /root/xfstests_bld/kvm-xfstesets
DIR=/root/xfstests_bld/kvm-xfstests

if [ "$(hostname)" = "xfstests-ltm" ]
then
    gsutil cat gs://$GS_BUCKET/gce-xfstests-cert.pem \
	   > $DIR/.gce_xfstests_cert.pem
    echo "GCE_LTM_SERVER_CERT=$DIR/.gce_xfstests_cert.pem" > $DIR/.ltm_instance
    echo "GCE_LTM_NAME=$(hostname)" >> $DIR/.ltm_instance
    echo "GCE_LTM_EXT_IP=127.0.0.1" >> $DIR/.ltm_instance
    echo -n "GCE_LTM_PWD=" >> $DIR/.ltm_instance
    gsutil cat gs://$GS_BUCKET/ltm-pass >> $DIR/.ltm_instance
fi
if [ "$(hostname)" = "xfstests-bldsrv" ]
then
    gsutil cat gs://$GS_BUCKET/gce-xfstests-cert.pem \
	   > $DIR/.gce_xfstests_cert.pem
    echo "GCE_LTM_SERVER_CERT=$DIR/.gce_xfstests_cert.pem" > $DIR/.bldsrv_instance
    echo "GCE_LTM_NAME=$(hostname)" >> $DIR/.bldsrv_instance
    echo "GCE_LTM_EXT_IP=127.0.0.1" >> $DIR/.bldsrv_instance
    echo -n "GCE_LTM_PWD=" >> $DIR/.bldsrv_instance
    gsutil cat gs://$GS_BUCKET/ltm-pass >> $DIR/.bldsrv_instance
fi
touch $DIR/config.common
cp "$GCE_CONFIG_FILE" $DIR/config.gce

exit 0
