/*
Webserver endpoints for the gce-xfstests LTM (lightweight test manager).

This stand-alone server handles requests sent by the client-side scripts.
The endpoints are:
	/login (deprecated) - to authenticate a user session, enforced by the flask
	webserver in the previous implementation.

	/gce-xfstests - takes in a json POST in the form of LTMRequest, and runs the
	tests.

*/
package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"

	"gce-server/logging"
	"gce-server/server"

	"github.com/sirupsen/logrus"
)

// configurable user name for naming LTM files
const (
	LTMUserName = "ltm"
)

/*
runTests is the end point for launching a gce-xfstests test.
orig_cmdline is a base64 encoding of the command line arguments.
A ShardSchedular is constructed to arrange the tests in multiple
ShardWorkers, and then starts these shards in separate go routines.

Returns the info generated by the sharder
*/
func runTests(w http.ResponseWriter, r *http.Request) {
	log := server.Log.WithField("endpoint", "/gce-xfstests")
	log.Info("Request received")

	defer server.FailureResponse(w)

	var c server.UserRequest
	err := json.NewDecoder(r.Body).Decode(&c)
	logging.CheckPanic(err, log, "Failed to parse json request")

	// TODO: implement password validation
	data, err := base64.StdEncoding.DecodeString(c.CmdLine)
	logging.CheckPanic(err, log, "Failed to decode cmdline")

	c.CmdLine = string(data)

	log.WithFields(logrus.Fields{
		"cmdline": c.CmdLine,
		"options": fmt.Sprintf("%+v", c.Options),
	}).Info("Receive test request")

	sharder := NewShardSchedular(c)
	sharder.Dump("/root/mock_sharder.json")
	// sharder := ReadSharder("/root/mock_sharder.json")

	log.Info("Test sharder created")
	sharder.StartTests()

	response := server.SimpleResponse{
		Status: true,
		Msg:    sharder.testID,
	}
	log.WithField("response", response).Info("Test sharder started")
	js, _ := json.Marshal(response)
	w.Header().Set("Content-Type", "application/json")
	w.Write(js)
}

func main() {
	defer logging.CloseLog(server.Log)

	server.Log.Info("Launching LTM server")
	http.HandleFunc("/", server.Index)
	http.HandleFunc("/login", server.Login)
	http.HandleFunc("/gce-xfstests", runTests)
	err := http.ListenAndServeTLS(":443", server.CertPath, server.SecretPath, nil)
	logging.CheckPanic(err, server.Log, "TLS server failed to launch")
}
