#!/bin/bash

DIR=..
if test -n "$GCE_XFSTESTS_DIR"
then
    DIR="$GCE_XFSTESTS_DIR"
fi
. "$DIR/util/get-config"
. "$DIR/util/parse_opt_funcs"

TYPE=config
ARCH=x86_64

while [ "$1" != "" ];
do
    case "$1" in
	--perf)
	    TYPE=perf-config
	    ;;
	--blktests)
	    DO_BLKTESTS=yes
	    ;;
	--i386)
	    ARCH=i386
	    ;;
	--no-action)
	    NO_ACTION="echo"
	    ;;
	--debug)
	    DO_DEBUG=yes
	    ;;
	--help|help)
	    echo "Usage: install-kconfig [--i386] [--perf] [--blktests]"
	    echo "	[--debug] [--no-action]"
	    exit 0
	    ;;
	*)
	    echo "unknown option: $1"
	    exit 1
	    ;;
    esac
    shift
done

if test ! -f MAINTAINERS -o ! -f Makefile ; then
   echo "Not at top-level of kernel sources"
   exit 1
fi

if test -f .git/kbuild/config ; then
    if test "$ARCH" = i386 ; then
	BLD_DIR=$(sed -ne 's/^BLD_DIR_32=//p' .git/kbuild/config);
    else
	BLD_DIR=$(sed -ne 's/^BLD_DIR=//p' .git/kbuild/config);
    fi
    mkdir -p "$BLD_DIR"
fi
if test -z "$BLD_DIR" ; then
   BLD_DIR=.
fi

# echo "Build directory is $BLD_DIR"

KVER=$(make kernelversion)

if test -z "$KVER" ; then
    echo "Unable to determine kernel version"
    exit 1
fi

VERSION=$(echo $KVER | awk -F. '{print $1}')
SUBVERSION=$(echo $KVER | awk -F. '{print $2}')

# echo "Kernel version is $KVER - $VERSION $SUBVERSION"

CONFIG_FN=''
KCONFIG_DIR=$(dirname $DIR)/kernel-configs
while test -z "$CONFIG_FN" ; do
    fn="$KCONFIG_DIR/$ARCH-$TYPE-$VERSION.$SUBVERSION"
    if test -f "$fn" ; then
	CONFIG_FN=$fn
    fi
    SUBVERSION=$(($SUBVERSION - 1))
    if test $SUBVERSION = 0 ; then
	VERSION=$(($VERSION - 1))
	SUBVERSION=20
    fi
    if test $VERSION = 2 ; then
	echo "Can't find configuration file?"
	exit 1
    fi
done

# echo "Config file is $CONFIG_FN"

if test -n "$DO_BLKTESTS" ; then
    BLKTESTS_CONFIG="$KCONFIG_DIR/blktests-configs"
else
    BLKTESTS_CONFIG=/dev/null
fi

if test -n "$DO_DEBUG" ; then
    DEBUG_CONFIGS="$KCONFIG_DIR/extra-debug-configs"
else
    DEBUG_CONFIGS=/dev/null
fi

if test -f "$BLD_DIR/.config" ; then
    mv "$BLD_DIR/.config" "$BLD_DIR/.config.bak"
fi
if test -z "$NO_ACTION" ; then
    cat "$CONFIG_FN" "$BLKTESTS_CONFIG" "$DEBUG_CONFIGS" > "$BLD_DIR/.config"
else
    echo cat "$CONFIG_FN" "$BLKTESTS_CONFIG" "$DEBUG_CONFIGS" \> "$BLD_DIR/.config"
fi

if test -z "$BLD_DIR" ; then
    $NO_ACTION make "ARCH=$ARCH" olddefconfig
else
    $NO_ACTION make "O=$BLD_DIR" "ARCH=$ARCH" olddefconfig
fi

exit 0
