#!/bin/bash -vx

if test -f config.custom ; then
	. config.custom
else
	. config
fi

nr_cpus=$(expr 1 + $(grep ^processor /proc/cpuinfo | tail -1 | \
		sed -e 's/.*://') )
J=-j$(expr $nr_cpus \* 2)

DESTDIR=$(pwd)/bld

mkdir -p $DESTDIR

(cd e2fsprogs-libs; \
    CFLAGS="$CCF -I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    ./configure --prefix=/; make $J; make DESTDIR=$DESTDIR $J install)

(cd attr; \
    CFLAGS="$CCF -I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    ./configure --prefix=$DESTDIR; \
    make $J ; \
    make $J install-dev ; make install)

(cd acl; \
    CPPFLAGS="-I$DESTDIR/include" \
    CFLAGS="$CCF -I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    ./configure --prefix=$DESTDIR; \
    make $J LLDFLAGS=-all-static LIBTOOL="/usr/bin/libtool --tag=CC" ; \
    make $J install-dev ; \
    make $J install)

(cd libaio; make $J prefix=$DESTDIR install)

rm $DESTDIR/lib/libaio.so*

(cd xfsprogs-dev; make $J realclean ; make $J configure ; \
    CFLAGS="$CCF -I$DESTDIR/include" \
    CPPFLAGS="-I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    LIBS=-lpthread \
    ./configure --prefix=/ --disable-lib64 ; \
    make $J LLDFLAGS=-all-static BUILD_VERBOSE=1; \
    DIST_ROOT=$DESTDIR make $J install; \
    DIST_ROOT=$DESTDIR make $J install-dev)

(cd dmapi; \
    CFLAGS="$CCF -I$DESTDIR/include" \
    CPPFLAGS="-I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    ./configure --prefix=$DESTDIR; \
    make $J LLDFLAGS=-all-static LIBTOOL="/usr/bin/libtool --tag=CC" ; \
    make $J install-dev; make $J install)

find . -name \*.la | xargs rm -f      # Die, libtool, die!!!!
cp $DESTDIR/include/xfs/dmapi.h $DESTDIR/include

(cd fio; \
    export CFLAGS="$CCF -I$DESTDIR/include" ; \
    export LDFLAGS="$EXEC_LDFLAGS -L$DESTDIR/lib" ; \
    ./configure; make V=1 prefix=/ $J; make prefix=/ V=1 DESTDIR=$DESTDIR $J install)

(cd xfstests-dev; \
    autoheader ; autoconf ; \
    CFLAGS="$CCF -I$DESTDIR/include -fno-stack-protector"
    CPPFLAGS="-I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    LIBS=-lpthread \
    ./configure ; \
    make $J LLDFLAGS=$EXEC_LLDFLAGS LIBTOOL="/usr/bin/libtool --tag=CC" BUILD_VERBOSE=1)

(cd quota; \
    export CFLAGS="$CCF -I$DESTDIR/include" ; \
    export LDFLAGS="$EXEC_LDFLAGS -L$DESTDIR/lib $EXEC_LDFLAGS" ; \
    export CPPFLAGS="-I$DESTDIR/include" \
    aclocal ; autoconf ; \
    ./configure --prefix=$DESTDIR ; \
    make V=1 $J; make V=1 $J install)
