#!/bin/bash

. build_config.sh

BUILD_DIR=build-release

function usage()
{
    echo "Usage: build-all-arches: [--readme-only]"
    exit 1
}

while [ "$1" != "" ]; do
    case $1 in
	--readme-only)
	    README_ONLY=yes
	    ;;
	--resume-arch)
	    shift
	    RESUME_ARCH="$1"
	    ;;
	*)
	    usage
	    exit 1
	    ;;
    esac
    shift
done

mkdir -p out_dir

(cd $dir ; ./get-versions ) > git-versions

release=$(cd $BUILD_DIR/xfstests-dev ; git tag --points-at HEAD | grep ^release)

sed -e "s;@MIRROR@;$MIRROR;" \
	-e "s/@XFSTESTS_RELEASE@/$release/" \
	-e "/@VERFILE@/r git-versions" \
	< README.in | sed -e '/^@VERFILE@$/d' > out_dir/README

if test "$README_ONLY" = "yes" ; then
    exit 0
fi

(cd $BUILD_DIR ; git pull ; ./get-all )

date
for i in "${ARCH_LIST[@]}" ; do
    if test -n "$RESUME_ARCH" ; then
	if test "$i" != "$RESUME_ARCH"; then
	    echo "Resume_arch skipping $i"
	    continue;
	else
	    RESUME_ARCH=
	fi
    fi
    echo "----------------- $(date '+%Y-%m-%d %H:%M:%S'): Starting $i"
    date
    echo "CHROOT=stretch-$i" > $BUILD_DIR/config.custom
    sed -e '1,/^#BEGIN CONFIG.CUSTOM/d' < build_config.sh \
	>> $BUILD_DIR/config.custom
    case $i in
	arm*)
	    echo OUT_TAR=yes >> $BUILD_DIR/config.custom
	    echo export ACCEL_BIN=/usr/local/bin-accel \
		 >> $BUILD_DIR/config.custom
	    ;;
    esac
    echo "MIRROR=$MIRROR" > $BUILD_DIR/kvm-xfstests/test-appliance/config.custom

    if ! (cd $BUILD_DIR ; ./do-all) ; then
	echo "Build of $i failed!"
	exit 1
    fi
    case $i in
	arm*)
	    fn=root_fs.tar.gz
	    artifact=root_fs.$i.tar.gz
	    ;;
	*)
	    fn=root_fs.img
	    artifact=root_fs.img.$i
	    ;;
    esac
    cp $BUILD_DIR/kvm-xfstests/test-appliance/$fn out_dir/$artifact
    cp $BUILD_DIR/xfstests.tar.gz out_dir/xfstests-$i.tar.gz
    cp $BUILD_DIR/xfstests/git-versions out_dir/git-versions-$i
done

echo "----------------- $(date '+%Y-%m-%d %H:%M:%S'): Finished"
