#!/bin/bash

ARCHS=(build-64 build-32 build-armhf)

for i in "${ARCHS[@]}" ; do
    (cd $i ; ./get-versions | \
	 egrep -v "^(stress-ng)|(keyutils)") > git-versions-$i
    if ! diff git-versions-"${ARCHS[0]}" git-versions-$i
    then
	echo "WARNING: differences in versions detected"
	exit 1
    fi
done

date
for i in "${ARCHS[@]}" ; do
    echo "----------------- $(date '+%Y-%m-%d %H:%M:%S'): Starting $i"
    (cd $i ; ./do-all)
    date
    egrep -v "^(stress-ng)|(keyutils)" $i/xfstests/git-versions > git-versions-$i
    if ! diff git-versions-"${ARCHS[0]}" git-versions-$i
    then
	echo "WARNING: differences in versions detected"
	exit 1
    fi
done

echo "----------------- $(date '+%Y-%m-%d %H:%M:%S'): Finished"
