#!/bin/bash

ARCHS=(build-64 build-32 build-armhf)

for i in "${ARCHS[@]}" ; do
    (cd $i ; ./get-versions | grep -v ^stress-ng) > git-versions-$i
    if ! diff git-versions-"${ARCHS[0]}" git-versions-$i
    then
	echo "WARNING: differences in versions detected"
	exit 1
    fi
done

date
for i in "${ARCHS[@]}" ; do
    echo "Building for $i"
    (cd $i ; ./do-all)
    date
    grep -v ^stress-ng $i/xfstests/git-versions > git-versions-$i
    if ! diff git-versions-"${ARCHS[0]}" git-versions-$i
    then
	echo "WARNING: differences in versions detected"
	exit 1
    fi
done

date
