#!/bin/bash -vx

. config

nr_cpus=$(expr 1 + $(grep ^processor /proc/cpuinfo | tail -1 | \
		sed -e 's/.*://') )
J=-j$(expr $nr_cpus \* 2)

DESTDIR=$(pwd)/bld

mkdir -p $DESTDIR

(cd e2fsprogs-libs; \
    CFLAGS="$CCF -I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    ./configure --prefix=/; make $J; make DESTDIR=$DESTDIR $J install)

(cd attr; \
    CFLAGS="$CCF -I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    ./configure --prefix=$DESTDIR; \
    make $J LLDFLAGS=-all-static ; \
    make $J install-dev ; make install)

(cd acl; \
    CPPFLAGS="-I$DESTDIR/include" \
    CFLAGS="$CCF -I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    ./configure --prefix=$DESTDIR; \
    make $J LLDFLAGS=-all-static ; \
    make $J install-dev ; \
    make $J install)

(cd libaio; make $J prefix=$DESTDIR install)

(cd xfsprogs-dev; make $J realclean ; make $J configure ; \
    CFLAGS="$CCF -I$DESTDIR/include" \
    CPPFLAGS="-I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    LIBS=-lpthread \
    ./configure --prefix=/; \
    make LLDFLAGS=-all-static BUILD_VERBOSE=1; \
    DIST_ROOT=$DESTDIR make install; \
    DIST_ROOT=$DESTDIR make install-dev)

(cd dmapi; \
    CFLAGS="$CCF -I$DESTDIR/include" \
    CPPFLAGS="-I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    ./configure --prefix=$DESTDIR; \
    LIBTOOL="/usr/bin/libtool --tag=CC" make LLDFLAGS=-all-static; \
    make $J install-dev; make $J install)

find . -name \*.la | xargs rm -f      # Die, libtool, die!!!!
cp $DESTDIR/include/xfs/dmapi.h $DESTDIR/include

(cd xfstests-dev; \
    autoheader ; autoconf ; \
    CFLAGS="$CCF -I$DESTDIR/include -fno-stack-protector"
    CPPFLAGS="-I$DESTDIR/include" \
    LDFLAGS="-static -L$DESTDIR/lib" \
    LIBS=-lpthread \
    ./configure ; \
    make $J LLDFLAGS=-all-static BUILD_VERBOSE=1)

