#!/bin/bash

. build_config.sh

TOP_DIR=build-release
BUILD_DIR=$TOP_DIR/fstests-bld

function usage()
{
    echo "Usage: build-all-arches: [--readme-only] [--resume-arch <arch>]"
    exit 1
}

function gen_README()
{
	sed -e "s;@MIRROR@;$MIRROR;" \
		-e "s/@XFSTESTS_RELEASE@/$xfstests_rel/" \
		-e "s/@BLKTESTS_RELEASE@/$blktests_rel/" \
		-e "/@VERFILE@/r git-versions" \
		< README.in | sed -e '/^@VERFILE@$/d' > out_dir/README
}

while [ "$1" != "" ]; do
    case $1 in
	--readme-only)
	    README_ONLY=yes
	    ;;
	--resume-arch)
	    shift
	    RESUME_ARCH="$1"
	    ;;
	*)
	    usage
	    exit 1
	    ;;
    esac
    shift
done

mkdir -p out_dir
rm -f out_dir/README

sed -e '1,/^#BEGIN CONFIG.CUSTOM/d' < build_config.sh \
	>> $BUILD_DIR/config.custom
(cd $BUILD_DIR ; git pull ; ./get-all )
(cd $BUILD_DIR ; ./get-versions ) > git-versions

xfstests_rel=$(cd $BUILD_DIR/xfstests-dev ; git tag --points-at HEAD | grep ^release)
blktests_rel=$(cd $BUILD_DIR/blktests ; git tag --points-at HEAD | grep ^release)

if test "$README_ONLY" = "yes" ; then
    gen_README
    exit 0
fi

date
for i in "${ARCH_LIST[@]}" ; do
    if test -n "$RESUME_ARCH" ; then
	if test "$i" != "$RESUME_ARCH"; then
	    echo "Resume_arch skipping $i"
	    continue;
	else
	    RESUME_ARCH=
	fi
    fi
    echo "----------------- $(date '+%Y-%m-%d %H:%M:%S'): Starting $i"
    date
    echo "CHROOT=$DISTRO-$i" > $BUILD_DIR/config.custom
    sed -e '1,/^#BEGIN CONFIG.CUSTOM/d' < build_config.sh \
	>> $BUILD_DIR/config.custom
    echo "CHROOT=$DISTRO-$i" > $TOP_DIR/config.custom
    sed -e '1,/^#BEGIN BUILD-CONFIG/d' < build_config.sh \
	>> $TOP_DIR/config.custom
    case $i in
	arm*)
	    echo export ACCEL_BIN=/usr/local/bin-accel \
		 >> $BUILD_DIR/config.custom
	    ;;
    esac
    echo "MIRROR=$MIRROR" > $TOP_DIR/test-appliance/config.custom

    if ! (cd $TOP_DIR ; ./build-appliance) ; then
	echo "Build of $i failed!"
	exit 1
    fi
    cp $TOP_DIR/test-appliance/root_fs.tar.gz out_dir/root_fs.$i.tar.gz
    cp $TOP_DIR/test-appliance/root_fs.img out_dir/root_fs.img.$i
    cp $BUILD_DIR/xfstests.tar.gz out_dir/xfstests-$i.tar.gz
    cp $BUILD_DIR/xfstests/git-versions out_dir/git-versions-$i
    if test ! -f out_dir/README ; then
	gen_README
    fi
done

echo "----------------- $(date '+%Y-%m-%d %H:%M:%S'): Finished"
