#!/bin/bash

if test -f config.custom ; then
	. config.custom
else
	. config
fi

echo "xfstests-bld	$(git describe --always --dirty) ($(git log -1 --pretty=%cD))" > xfstests-bld.ver
cat *.ver > xfstests/git-versions
cd kvm-xfstests/test-appliance
$SUDO_ENV ./gen-image --update
