#!/bin/bash

if test -f config.custom ; then
	. config.custom
else
	. config
fi

if test ! -d xfsprogs-dev
then
	if test -z "$XFSPROGS_GIT"; then
		echo "XFSPROGS_GIT not set; check your config file!"
		exit 1
        fi
	if ! git clone $XFSPROGS_GIT xfsprogs-dev; then
		echo "Failed to get xfsprogs-dev from $XFSPROGS_GIT"
                exit 1
	fi
	if test -n "$XFSPROGS_COMMIT"; then
		cd xfsprogs
		git branch xfstests-bld $XFSPROGS_COMMIT
		git checkout xfstests-bld
		cd ..
	fi
fi
if test ! -d xfstests-dev
then
	if test -z "$XFSTESTS_GIT"; then
		echo "XFSTESTS_GIT not set; check your config file!"
		exit 1
        fi
	if ! git clone $XFSTESTS_GIT xfstests-dev; then
		echo "Failed to get xfstests-dev from $XFSTESTS_GIT"
                exit 1
	fi
	if test -n "$XFSTESTS_COMMIT"; then
		cd xfstests-dev
		git branch xfstests-bld $XFSTESTS_COMMIT
		git checkout xfstests-bld
		cd ..
	fi
fi
if test ! -d fio
then
	if test -z "$FIO_GIT"; then
		echo "FIO_GIT not set; check your config file!"
		exit 1
        fi
	if ! git clone $FIO_GIT fio; then
		echo "Failed to get fio from $FIO_GIT"
                exit 1
	fi
	if test -n "$FIO_COMMIT"; then
		cd fio
		git branch xfstests-bld $FIO_COMMIT
		git checkout xfstests-bld
		cd ..
	fi
fi
if test ! -d quota
then
	if test -z "$QUOTA_GIT"; then
		echo "QUOTA_GIT not set; check your config file!"
		exit 1
        fi
	if ! git clone $QUOTA_GIT quota; then
		echo "Failed to get fio from $QUOTA_GIT"
                exit 1
	fi
	if test -n "$QUOTA_COMMIT"; then
		cd quota
		git branch xfstests-bld $QUOTA_COMMIT
		git checkout xfstests-bld
		cd ..
	fi
fi

# Make sure acl doesn't try regenerate these files because of the
# vagrancies of the timestamps when they were checked out
touch acl/aclocal.m4 acl/configure acl/Makefile.in
