#!/bin/bash

. config

if test ! -d xfsprogs-dev
then
	if test -z "$XFSPROGS_GIT"; then
		echo "XFSPROGS_GIT not set; check your config file!"
		exit 1
        fi
	if ! git clone $XFSPROGS_GIT xfsprogs-dev; then
		echo "Failed to get xfsprogs-dev from $XFSPROGS_GIT"
                exit 1
	fi
fi
if test ! -d xfstests-dev
then
	if test -z "$XFSTESTS_GIT"; then
		echo "XFSTESTS_GIT not set; check your config file!"
		exit 1
        fi
	if ! git clone $XFSTESTS_GIT xfstests-dev; then
		echo "Failed to get xfstests-dev from $XFSTESTS_GIT"
                exit 1
	fi
fi
if test ! -d fio
then
	if test -z "$FIO_GIT"; then
		echo "FIO_GIT not set; check your config file!"
		exit 1
        fi
	if ! git clone $FIO_GIT fio; then
		echo "Failed to get fio from $FIO_GIT"
                exit 1
	fi
fi
