#!/bin/bash

rsync -avH --delete debs xfstests-bld/xfstests-bld/kvm-xfstests/test-appliance
date
schroot -b -c jessie -n tytso-jessie
date
dd-schroot-cmd -y -c tytso-jessie apt-get install build-essential \
	autoconf autoconf2.64 automake libgdbm-dev libtool-bin \
	qemu-utils gettext e2fslibs-dev git debootstrap \
	fakechroot libdbus-1-3 autopoint pkg-config symlinks rsync ccache
cd ~/xfstests-bld/xfstests-bld
schroot -r -c tytso-jessie -- bash -c "date ; make clean ; date ; make ; date ; make tarball ; date ; cd kvm-xfstests/test-appliance ; ./gen-image --out-tar ; date"
schroot -e -c tytso-jessie
date


