#!/bin/bash

. build_config.sh

for i in "${ARCH_LIST[@]}" ; do
    dir="build-$i"
    if ! test -d $dir ; then
	echo "Skipping $i"
	continue
    fi
    echo Setting up $i
    echo "CHROOT=stretch-$i" > $dir/config.custom
    sed -e '1,/^#BEGIN CONFIG.CUSTOM/d' < build_config.sh >> $dir/config.custom
    case $i in
	arm*)
	    echo OUT_TAR=yes >> $dir/config.custom
	    ;;
    esac
    (cd $dir ; git pull ; ./get-all )
    echo "MIRROR=$MIRROR" > $dir/kvm-xfstests/test-appliance/config.custom
    if test -f e2fsprogs.ver ; then
	cp e2fsprogs.ver $dir
    fi
done
