#!/bin/bash

. build_config.sh

for i in "${ARCH_LIST[@]}" ; do
    dir="build-$i"
    if ! test -d $dir ; then
	echo "Skipping $i"
	continue
    fi
    (cd $dir ; ./get-versions | \
	 egrep -v "^(stress-ng)|(keyutils)|(syzkaller)") > git-versions-$i
done

for i in "${ARCH_LIST[@]}" ; do
    dir="build-$i"
    if ! test -d $dir ; then
	continue
    fi
    if ! diff git-versions-"${ARCH_LIST[0]}" git-versions-$i
    then
	echo "WARNING: differences in versions detected: ${ARCH_LIST[0]} vs $i"
	exit 1
    fi
done

