#!/bin/bash
#
# This script fetches the self-signed SSL cert from the user's configured
# GS_BUCKET before lighttpd is allowed to start.
. /usr/local/lib/gce-funcs
gcs_cp gs://$GS_BUCKET/gce-xfstests-server.pem /etc/lighttpd/server.pem
/usr/local/lib/gce-logger "fetching cert completed, gcs_cp returned $?"

gcs_cp gs://$GS_BUCKET/gce_xfstests.config "$GCE_CONFIG_FILE"
/usr/local/lib/gce-logger "fetching config completed, gcs_cp returned $?"

chmod 0400 /etc/lighttpd/server.pem

# Set up the necessary configuration files for the gce-xfstests script
# installed in /root/xfstests_bld/run-fstesets
DIR=/root/xfstests_bld/run-fstests

. "$GCE_CONFIG_FILE"

if gce_attribute gce_xfs_ltm
then
    gcs_cat gs://$GS_BUCKET/gce-xfstests-cert.pem \
	   > $DIR/.gce_xfstests_cert_$GCE_PROJECT.pem
    echo "GCE_LTM_SERVER_CERT=$DIR/.gce_xfstests_cert_$GCE_PROJECT.pem" > $DIR/.ltm_instance_$GCE_PROJECT
    echo "GCE_LTM_NAME=$instance" >> $DIR/.ltm_instance_$GCE_PROJECT
    echo "GCE_LTM_EXT_IP=127.0.0.1" >> $DIR/.ltm_instance_$GCE_PROJECT
    echo -n "GCE_LTM_PWD=" >> $DIR/.ltm_instance_$GCE_PROJECT
    gcs_cat gs://$GS_BUCKET/ltm-pass >> $DIR/.ltm_instance_$GCE_PROJECT
elif gce_attribute gce_xfs_kcs
then
    gcs_cat gs://$GS_BUCKET/gce-xfstests-cert.pem \
	   > $DIR/.gce_xfstests_cert_$GCE_PROJECT.pem
    echo "GCE_KCS_SERVER_CERT=$DIR/.gce_xfstests_cert_$GCE_PROJECT.pem" > $DIR/.kcs_instance_$GCE_PROJECT
    echo "GCE_KCS_NAME=$instance" >> $DIR/.kcs_instance_$GCE_PROJECT
    echo "GCE_KCS_EXT_IP=127.0.0.1" >> $DIR/.kcs_instance_$GCE_PROJECT
    echo -n "GCE_KCS_PWD=" >> $DIR/.kcs_instance_$GCE_PROJECT
    gcs_cat gs://$GS_BUCKET/ltm-pass >> $DIR/.kcs_instance_$GCE_PROJECT
fi
touch $DIR/config.common
cat "$GCE_CONFIG_FILE" >> $DIR/config.gce
echo SKIP_GS_CONFIG_UPDATE=yes >> $DIR/config.gce

# Create send_mail.ini in /run if SMTP or SendGrid configuration is present
cp /dev/null "$SEND_MAIL_INI"
chmod 0600 "$SEND_MAIL_INI"
if [ -n "$SENDGRID_API_KEY" ]; then
    echo "[sendgrid]" >> "$SEND_MAIL_INI"
    echo "api_key = $SENDGRID_API_KEY" >> "$SEND_MAIL_INI"
fi
if [ -n "$SMTP_SERVER" -a -n "$SMTP_USER" -a -n "$SMTP_PASSWORD" ] ; then
    if [ -s "$SEND_MAIL_INI" ] ; then
        echo "" >> "$SEND_MAIL_INI"
    fi

    echo "[smtp]" >> "$SEND_MAIL_INI"
    [ -n "$SMTP_SERVER" ] && echo "server = $SMTP_SERVER" >> "$SEND_MAIL_INI"
    [ -n "$SMTP_PORT" ] && echo "port = $SMTP_PORT" >> "$SEND_MAIL_INI"
    [ -n "$SMTP_USER" ] && echo "user = $SMTP_USER" >> "$SEND_MAIL_INI"
    [ -n "$SMTP_PASSWORD" ] && echo "password = $SMTP_PASSWORD" >> "$SEND_MAIL_INI"
    [ -n "$SMTP_CAFILE" ] && echo "cafile = $SMTP_CAFILE" >> "$SEND_MAIL_INI"
    [ -n "$TLS_MODE" ] && echo "tls_mode = $TLS_MODE" >> "$SEND_MAIL_INI"
fi
if [ -s "$SEND_MAIL_INI" -a -n "$GCE_REPORT_SENDER" ] ; then
    if ! grep -q "\[smtp\]" "$SEND_MAIL_INI" ; then
        echo "" >> "$SEND_MAIL_INI"
	echo "[smtp]" >> "$SEND_MAIL_INI"
    fi
    echo "sender = $GCE_REPORT_SENDER" >> "$SEND_MAIL_INI"
fi
if [ ! -s "$SEND_MAIL_INI" ] ; then
    rm "$SEND_MAIL_INI"
fi
exit 0
