#!/bin/bash

DIR=..
. $DIR/config

if test -r config.custom ; then
   . ./config.custom
fi

if test -z "$GS_BUCKET" -o -z "$GCE_PROJECT" -o -z "$GCE_ZONE"
then
	echo "You must configure GS_BUCKET, GCE_PROJECT, and GCE_ZONE in"
	echo "your config file"
	exit 1
fi

GS_RW=https://www.googleapis.com/auth/devstorage.read_write
GS_RO=https://www.googleapis.com/auth/devstorage.read_only
LOG_WR=https://www.googleapis.com/auth/logging.write
COMPUTE_RW=https://www.googleapis.com/auth/compute

SCOPES="$GS_RW,$LOG_WR,$COMPUTE_RW"

IMAGE=https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-8

TARBALL=../../xfstests.tar.gz

if ! test -f $TARBALL ; then
   echo $TARBALL does not exist!
   exit 1
fi

while [ "$1" != "" ];
do
    case $1 in
	--fast)
	    fast=yes
	    ;;
	*)
	    echo "unknown option: $1"
	    exit 1
	    ;;
    esac
    shift
done

GS_SCRIPT=gs://$GS_BUCKET/gce-xfstests-bld.sh
GS_TARBALL=gs://$GS_BUCKET/xfstests.tar.gz
METADATA="startup-script-url=$GS_SCRIPT"
MACHTYPE=n1-highmem-2

if test "$fast" = "yes"
then
    METADATA="$METADATA fast=yes"
    MACHTYPE=n1-standard-1
fi

LOCAL_HASH=$(gsutil hash $TARBALL 2> /dev/null |  grep "Hash (md5)" | awk '{print $3}')
REMOTE_HASH=$(gsutil stat $GS_TARBALL 2> /dev/null | grep "Hash (md5)" | awk '{print $3}')
if test "$LOCAL_HASH" != "$REMOTE_HASH"
then
	gsutil cp $TARBALL $GS_TARBALL
fi

t=$(mktemp /tmp/gce-create.XXXXXXXX)

sed -e "s/@BUCKET@/$GS_BUCKET/" < gce-xfstests-bld.sh > $t
gsutil cp $t gs://$GS_BUCKET/gce-xfstests-bld.sh

# Update the git-versions file
if test -d ../../xfstests
then
    echo "xfstests-bld	$(git describe --always --dirty) ($(git log -1 --pretty=%cD))" \
	 > ../../xfstests-bld.ver
    cat ../../*.ver > files/root/xfstests/git-versions
fi

tar -X gce-exclude-files -C files -cf - . | gzip -9n > $t
GS_FILES_TARBALL=gs://$GS_BUCKET/files.tar.gz

LOCAL_HASH=$(gsutil hash $t 2> /dev/null |  grep "Hash (md5)" | awk '{print $3}')
REMOTE_HASH=$(gsutil stat $GS_FILES_TARBALL 2> /dev/null | grep "Hash (md5)" | awk '{print $3}')
if test "$LOCAL_HASH" != "$REMOTE_HASH"
then
	gsutil cp $t $GS_FILES_TARBALL
fi
rm -f $t

gcloud compute --project "$GCE_PROJECT" -q instances delete xfstests-bld \
       --zone "$GCE_ZONE" 2> /dev/null
gcloud compute --project "$GCE_PROJECT" -q disks delete xfstests-bld 2> /dev/null

gcloud compute --project "$GCE_PROJECT" instances create "xfstests-bld" \
       --zone "$GCE_ZONE" --machine-type $MACHTYPE \
       --network "default" --metadata "^ ^$METADATA" \
       --maintenance-policy "MIGRATE" \
       --scopes "$SCOPES" --image "$IMAGE" \
       --boot-disk-type "pd-standard" --boot-disk-device-name "xfstests-bld"

echo -n "Waiting for bootable image setup."

cnt=0
while gcloud compute --project "$GCE_PROJECT" instances \
	     describe xfstests-bld --zone $GCE_ZONE >& /dev/null
do
    let cnt=$cnt+1
    if test $cnt -ge 10
    then
	echo -n "."
	cnt=0
    fi
    sleep 1
done
echo " Done!"

gcloud compute --project "$GCE_PROJECT" -q images delete xfstests
if test "$fast" = "yes"
then
    gcloud compute --project "$GCE_PROJECT" -q images create xfstests \
	   --description "Linux Kernel File System Test Appliance" \
	   --source-disk xfstests-bld --source-disk-zone "$GCE_ZONE"
    gcloud compute --project "$GCE_PROJECT" -q disks delete xfstests-bld \
	   --zone "$GCE_ZONE"
else
    gcloud compute --project "$GCE_PROJECT" -q images create xfstests \
	   --description "Linux Kernel File System Test Appliance" \
	   --source-uri gs://$GS_BUCKET/gce-xfstests.image.tar.gz
fi
