#!/bin/bash

if test -r config.custom ; then
   . $(pwd)/config.custom
fi

if test -z "$GCE_PROJECT" -o -z "$GCE_ZONE"
then
	echo "You must configure GCE_PROJECT and GCE_ZONE in"
	echo "the config.custom file"
	exit 1
fi

GS_RW=https://www.googleapis.com/auth/devstorage.read_write
GS_RO=https://www.googleapis.com/auth/devstorage.read_only
LOG_WR=https://www.googleapis.com/auth/logging.write
COMPUTE_RW=https://www.googleapis.com/auth/compute

SCOPES="$GS_RW,$COMPUTE_RW,$LOG_WR"

gcloud compute --project "$GCE_PROJECT" \
       instances create "xfstests" --zone "$GCE_ZONE" \
       --machine-type "n1-highcpu-4" --network "default" \
       --maintenance-policy "MIGRATE" \
       --scopes "$SCOPES" \
       --image "xfstests"
