#!/bin/sh
#
# This shell script must be run as root

SUITE=jessie
MIRROR=http://mirrors.kernel.org/debian
DIR=$(pwd)
ROOTDIR=$DIR/rootdir
#ARCH="--arch=i386"
RAW_ROOT_FS=$DIR/root_fs.raw
ROOT_FS=$DIR/root_fs.img
COMPAT="-o compat=0.10"

mkdir -p $ROOTDIR
mkdir -p var.cache.apt.archives
mkdir -p var.lib.apt.lists
cp /dev/null $RAW_ROOT_FS
mke2fs -t ext4 -O ^has_journal -Fq $RAW_ROOT_FS 1g
mount -t ext4 -o loop $RAW_ROOT_FS $ROOTDIR
mkdir -p $ROOTDIR/var/cache/apt/archives
mount --bind var.cache.apt.archives $ROOTDIR/var/cache/apt/archives
mkdir -p $ROOTDIR/var/lib/apt/lists
mount --bind var.lib.apt.lists $ROOTDIR/var/lib/apt/lists
debootstrap --variant=xfstests $ARCH $SUITE $ROOTDIR $MIRROR $DIR/kvm-xfstest.script
patch -p0 < config-patches
cp -r files/* rootdir
tar -C rootdir/root -xvf ../../xfstests.tar.gz
for i in vda vdb vdc vdd vde vdf results
do
	mkdir $ROOTDIR/$i
done

echo "fsgqa:x:31415:31415:fsgqa user:/home/fsgqa:/bin/sh" >> $ROOTDIR/etc/passwd
echo "fsgqa:*:31415:0:99999:7:::" >> $ROOTDIR/etc/shadow
echo "fsgqa:x:31415:" >> $ROOTDIR/etc/group
mkdir $ROOTDIR/home/fsgqa
chown 31415:31415 $ROOTDIR/home/fsgqa
chmod 755 $ROOTDIR/root

umount $ROOTDIR/var/cache/apt/archives
umount $ROOTDIR/var/lib/apt/lists
umount $ROOTDIR
rmdir $ROOTDIR

tune2fs -O has_journal $RAW_ROOT_FS
e2fsck -fy -E discard $RAW_ROOT_FS
qemu-img convert -f raw -O qcow2 $COMPAT -c $RAW_ROOT_FS $ROOT_FS
rm -f $RAW_ROOT_FS
