#!/bin/sh

# From https://github.com/GoogleCloudPlatform/compute-image-packages/releases

GCD_SHA256=dbff68c908ffe16aabcf7023d6121599996624a148f063309023f8cf8d4e2648
GCD_URL=https://github.com/GoogleCloudPlatform/compute-image-packages/releases/download/1.2.7/google-compute-daemon_1.2.7-1_all.deb

GSS_SHA256=728b7378ddfa89d803fdf908b5e5b7de02ddf8bd6bbe0c541b44c3286f37fb34
GSS_URL=https://github.com/GoogleCloudPlatform/compute-image-packages/releases/download/1.2.7/google-startup-scripts_1.2.7-1_all.deb

GIB_SHA256=837ef4b61e84e945b15b90d35dfeaa644b0ab62ce3117a73a8c3a01b0833ea59
GIB_URL=https://github.com/GoogleCloudPlatform/compute-image-packages/releases/download/1.2.7/python-gcimagebundle_1.2.7-1_all.deb


get_image () {
	url=$1
	exp_sha=$2

	file=$(basename $url)

	if test -e gce/$file && \
	   test $(sha256sum gce/$file | colrm 65) = $exp_sha ;
	then
		echo "$file has expected sha256"
		return 0;
	else
		curl -L -o gce/$file $url
		if test $(sha256sum gce/$file | colrm 65) != $exp_sha ;
		then
			echo "$file corrupted!?!"
			exit 1;
		fi	
	fi
}

get_image $GCD_URL $GCD_SHA256
get_image $GSS_URL $GSS_SHA256
get_image $GIB_URL $GIB_SHA256

	

