#!/bin/sh

GCD_SHA256=ddb561f7b43ff87066bb233f24c027b7dcd1c38be15f5f22735df98e880afe3f
GCD_URL=https://github.com/GoogleCloudPlatform/compute-image-packages/releases/download/1.2.0/google-compute-daemon_1.2.0-1_all.deb

GSS_SHA256=74dc35fc0cedeaac46381b3d3d8d3a4989ed02f3b475d532c744043d0968faef
GSS_URL=https://github.com/GoogleCloudPlatform/compute-image-packages/releases/download/1.2.0/google-startup-scripts_1.2.0-1_all.deb

GIB_SHA256=ead0323090aaa83cf53538409b0e465852684e45df5ca67529079a79f36bc1b0
GIB_URL=https://github.com/GoogleCloudPlatform/compute-image-packages/releases/download/1.2.0/python-gcimagebundle_1.2.0-1_all.deb

get_image () {
	url=$1
	exp_sha=$2

	file=$(basename $url)

	if test -e gce/$file && \
	   test $(sha256sum gce/$file | colrm 65) = $exp_sha ;
	then
		echo "$file has expected sha256"
		return 0;
	else
		curl -L -o gce/$file $url
		if test $(sha256sum gce/$file | colrm 65) != $exp_sha ;
		then
			echo "$file corrupted!?!"
			exit 1;
		fi	
	fi
}

get_image $GCD_URL $GCD_SHA256
get_image $GSS_URL $GSS_SHA256
get_image $GIB_URL $GIB_SHA256

	

