#!/bin/bash
if test -f /root/gce_zone
then
    ZONE=$(cat /root/gce_zone)
else
    ZONE=$(curl "http://metadata.google.internal/computeMetadata/v1/instance/zone" -H "Metadata-Flavor: Google" 2> /dev/null)
    ZONE=$(basename $ZONE)
fi

gcloud compute -q instances delete $(hostname) --zone $ZONE --delete-disks all
