.TH DMAPI 3
.SH NAME
dmapi \- \&DMAPI library
.SH SYNOPSIS
.nf
\f3#include <xfs/dmapi.h>\f1
.sp .8v
\f3cc ... \-D_FILE_OFFSET_BITS=64 \-D_GNU_SOURCE \-ldm
.fi
.SH DESCRIPTION
\f2DMAPI\f1, or \f2XDSM\f1, is an implementation of
the X/Open document:
\f3Systems Management: Data Storage Management (XDSM) API\f1
dated February 1997.
This interface is made available for the XFS filesystem
by means of the \f3libdm\f1 library.
.PP
See the XDSM manual at
http://www.opengroup.org/onlinepubs/9657099/toc.htm for a
description of the functions offered by libdm library.
.PP
For more information and details on how to contribute to the
XFS project see the web pages at:
http://oss.sgi.com/projects/xfs/
