#
# Copyright (c) 2000, 2002 Silicon Graphics, Inc.  All Rights Reserved.
#

TOPDIR = ..
include $(TOPDIR)/include/builddefs

LTLIBRARY = libmisc.la
LTLDFLAGS =

CFILES = quote.c unquote.c high_water_alloc.c next_line.c walk_tree.c

default: $(LTLIBRARY)
install install-dev install-lib:

include $(BUILDRULES)

