#!/bin/sh

DIR=.
. $DIR/config

. $DIR/util/parse_cli

if test -z "$DO_NET" ; then
   echo "Networking disabled."
elif test $(whoami) = "root" ; then
  NET="-net nic,model=virtio -net tap,script=$IFUP,downscript=$IFDOWN "
else
  NET="-netdev user,id=mynet0,net=172.20.0.0/24 -device virtio-net,netdev=mynet0 "
fi

#EXTRA_ARG="virtio_blk.queue_depth=32"

LOGFILE=$DIR/log.$(date +%Y%m%d%H%M)

SERIAL="-serial telnet::7500,server,nowait \
        -serial telnet::7501,server,nowait \
        -serial telnet::7502,server,nowait"

modprobe kvm-intel

if ! test -e $VDB -a -e $VDC -a -e $VDD -a -e $VDE -a -e $VDF -a -e $VDG
then
	echo "Test disks don't exist, running setup..."
	$DIR/setup
fi

$QEMU -boot order=c $NET \
	-drive file=$ROOT_FS,if=virtio$SNAPSHOT \
	-drive file=$VDB,cache=none,if=virtio \
	-drive file=$VDC,cache=none,if=virtio \
	-drive file=$VDD,cache=none,if=virtio \
	-drive file=$VDE,cache=none,if=virtio \
	-drive file=$VDF,cache=none,if=virtio \
	-drive file=$VDG,cache=none,if=virtio \
	-nographic -smp $NR_CPU -m $MEM \
        -serial mon:stdio \
         $SERIAL \
	--kernel $KERNEL \
	--append "root=$ROOT_DEV console=ttyS0,115200 $ARG $EXTRA_ARG" |\
tee $LOGFILE

$DIR/get-results $LOGFILE
echo "logfile in $LOGFILE"
