#!/bin/sh

DIR=.
if test -n "$KVM_XFSTESTS_DIR"
then
    DIR="$KVM_XFSTESTS_DIR"
fi

mkdir -p $DIR/disks
qemu-img create -f raw "$DIR/disks/vdb" 5g
qemu-img create -f raw "$DIR/disks/vdc" 5g
qemu-img create -f raw "$DIR/disks/vdd" 5g
qemu-img create -f raw "$DIR/disks/vde" 20g
qemu-img create -f raw "$DIR/disks/vdf" 20g
qemu-img create -f raw "$DIR/disks/vdg" 5g
qemu-img create -f raw "$DIR/disks/vdi" 1g
qemu-img create -f raw "$DIR/disks/vdj" 1g
/sbin/mke2fs -q -t ext4 -F "$DIR/disks/vdb"
/sbin/mke2fs -q -t ext4 -b 1024 -F "$DIR/disks/vdd"
/sbin/mke2fs -q -t ext4 -F "$DIR/disks/vdg"


