#!/bin/bash

. /usr/local/lib/gce-funcs

if ! test -f /etc/postfix/sasl_passwd
then
    sg_user=$(gce_attribute sg_user)
    sg_pass=$(gce_attribute sg_pass)
    if test -n "$sg_user" -a -n "$sg_pass"
    then
	echo "[smtp.sendgrid.net]:2525 $sg_user:$sg_pass" \
	     > /etc/postfix/sasl_passwd
	postmap /etc/postfix/sasl_passwd
	postfix reload
	gcloud compute instances -q add-metadata ${instance} \
	       --metadata "sg_pass="
    fi
fi

kexec=$(gce_attribute kexec)
if test -z "$kexec" || grep -q fstestcfg /proc/cmdline; then exit 0; fi

if ! test -f /root/bzImage
then
    if ! gsutil cp $kexec /root/bzImage
    then
	logger "Couldn't find $kexec"
	exit 1
    fi
    sync
fi

kopt=$(gce_attribute kopt)
mem=$(gce_attribute mem)
cpus=$(gce_attribute nr_cpus)
fstestcfg=$(gce_attribute fstestcfg)
fstestset=$(gce_attribute fstestset)
fstestopt=$(gce_attribute fstestopt)
fstesttz=$(gce_attribute fstesttz)
fstesttyp=$(gce_attribute fstesttyp)
fstestapi=$(gce_attribute fstestapi)

if test -n "$mem"
then
    kopt="$kopt mem=${mem}M"
fi

if test -n "$cpus"
then
    kopt="$kopt maxcpus=$cpus"
fi

kexec /root/bzImage --command-line="root=/dev/sda1 ro console=ttyS0,38400n8 elevator=noop console=ttyS0 $kopt fstestcfg=$fstestcfg fstestset=$fstestset fstestopt=$fstestopt fstesttz=$fstesttz fstesttyp=$fstesttyp fstestapi=$fstestapi"
