#!/bin/bash
set -e -x
# This script is used by the kernel compile server
# Environment variables can be set:
# GIT_REPO REPO_ID COMMIT GS_BUCKET BUILD_KERNEL

DIR=/root/repositories
REF_DIR="$DIR/linux.reference"

if test -z "$GIT_REPO"; then
    echo -e "GIT_REPO is not set"
    exit 1
fi

if test -z "$REPO_ID"; then
    REPO_ID=${GIT_REPO##*/}
fi

if test -z "$COMMIT"; then
    COMMIT="master"
fi

if test -z "$GS_BUCKET" -a -n "$BUILD_KERNEL"; then
    echo -e "GS_BUCKET is not set"
    exit 1
fi

if test -z "$GS_PATH"; then
    GS_PATH="gs://$GS_BUCKET/bzImage"
fi

# create reference repository if not exists
if [ ! -d "$REF_DIR" ]; then
    mkdir -p $DIR
    git clone --mirror https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git $REF_DIR
fi

REPO_DIR="$DIR/$REPO_ID"
if test -d "$REPO_DIR"; then
    rm -rf "$REPO_DIR"
fi

cd $DIR
git clone --reference $REF_DIR $GIT_REPO $REPO_DIR
gsutil cp "gs://$GS_BUCKET/build_config" "$REPO_DIR/.config"
cd $REPO_DIR
git checkout $COMMIT

if test -n "$BUILD_KERNEL"; then
    make olddefconfig
    make -j$(nproc)
    # copy image to gcs bucket
    gsutil cp "$REPO_DIR/arch/x86/boot/bzImage" $GS_PATH
fi
