#!/bin/bash
. /usr/local/lib/gce-funcs

status=$(echo $* | sed -e 's/^run xfstest //')
if test -f /run/fstest-config
then
    cfg="$(cat /run/fstest-config)"
    status="$cfg $status"
fi

if test -z "$(find /run/last_logged -mmin -1 -print 2> /dev/null)"
then
    gcloud compute instances -q add-metadata ${instance} \
	   --metadata "status=$(date +%H:%M) $status" >& /dev/null &
    touch /run/last_logged
fi
echo $(date +%H:%M) $status > /var/www/statusz
logger $cfg $*

