#!/bin/bash

. /usr/local/lib/gce-funcs

run_hooks pre-setup

/usr/local/lib/gce-logger disk setup
gce_attribute orig_cmdline | base64 -d > /var/www/cmdline

/usr/local/lib/gce-add-metadata "kernel_version=$(uname -a)" &

/usr/local/lib/gce-setup-results &
/usr/local/lib/gce-setup-scratch &

cat > /var/www/varz <<EOF
kernel_version $(uname -a)
nr_cpus $(cat /proc/cpuinfo  | grep ^processor | tail -n 1 | awk '{print $3 + 1}')
total_mem $(grep MemTotal /proc/meminfo | awk '{print $2 / 1024}')
FSTESTCFG $FSTESTCFG
FSTESTSET $FSTESTSET
FSTESTOPT $FSTESTOPT
FSTESTTYP $FSTESTTYP
FSTESTAPI $FSTESTAPI
FSTESTEXC $FSTESTEXC
MNTOPTS $MNTOPTS
EOF

hostname > /var/www/hostname.inc
for i in diskstats meminfo lockdep lock_stat slabinfo vmstat
do
    chmod 444 "/proc/$i"
done
chmod 644 /var/log/messages /var/log/syslog /var/log/kern.log

kexec=$(gce_attribute kexec)

case "$kexec" in
    *-onetime)
	gsutil rm "$kexec" &
	;;
esac

wait

cp /var/log/syslog /results/setup-syslog
cp /usr/local/lib/gce-syslog.conf /etc/rsyslog.d
systemctl restart rsyslog.service
dmesg >& /results/dmesg

for i in /usr/sbin/rsyslogd /usr/sbin/sshd
do
    pgrep -f $i | while read PID
    do
	echo -1000 > /proc/$PID/oom_score_adj
    done
done

run_hooks post-setup
