#!/bin/bash

. /usr/local/lib/gce-funcs
. /root/test-config
. /root/runtests_utils

logger -i "Entered setup scratch"

set -vx
SCRATCH_DSK=$instance-scratch
CREATED_SCRATCH_DEV=/dev/disk/by-id/google-scratch

# Use local SSD if available
if test -e /dev/disk/by-id/google-local-ssd-0
then
    CREATED_SCRATCH_DEV=/dev/disk/by-id/google-local-ssd-0
fi


if ! test -e $CREATED_SCRATCH_DEV
then
    if test -f "/run/do_blktests" ; then
	SCRATCH_SIZE=50
    else
	logger -i "compute partition sizes"
	# pass pri_tst size as 0, so TOTAL_SIZE doesn't include it.
	if compute_partition_sizes "/root/fs" 5 5 5 20 20; then
	    VDB_SIZE="${REQUIRED_PARTITION_SIZE["PRI_TST"]:-0}""g"
	    VDC_SIZE="${REQUIRED_PARTITION_SIZE["SM_SCR"]:-0}""g"
	    VDD_SIZE="${REQUIRED_PARTITION_SIZE["SM_TST"]:-0}""g"
	    VDE_SIZE="${REQUIRED_PARTITION_SIZE["LG_TST"]:-0}""g"
	    VDF_SIZE="${REQUIRED_PARTITION_SIZE["LG_SCR"]:-0}""g"
	    SCRATCH_SIZE=${REQUIRED_PARTITION_SIZE["TOTAL_SIZE"]}
	    if test "$SCRATCH_SIZE" -eq 0 ; then
		exit 0
	    fi
	    ((SCRATCH_SIZE+=1)) # Add 1gb for overhead.
	    logger -i "Computed partition sizes successfully:"
	    logger -i "VDC: $VDC_SIZE VDD: $VDD_SIZE"
	    logger -i "VDE: $VDE_SIZE VDF: $VDF_SIZE"
	    logger -i "Total disk size: $SCRATCH_SIZE"
	fi
    fi
    if test -n "$GCE_MIN_SCR_SIZE" -a -n "$SCRATCH_SIZE" && \
	[[ $GCE_MIN_SCR_SIZE =~ [0-9]* ]] && \
	(( GCE_MIN_SCR_SIZE < 250 )) && \
	(( GCE_MIN_SCR_SIZE > SCRATCH_SIZE )); then
	SCRATCH_SIZE=$GCE_MIN_SCR_SIZE
    fi

    gcloud compute -q disks create "$SCRATCH_DSK" \
	--size "${SCRATCH_SIZE:-100}" \
	--zone "$ZONE" --type "${SCRATCH_TYPE:-pd-ssd}"
    gcloud compute -q instances attach-disk ${instance} \
	--disk "$SCRATCH_DSK" \
	--device-name scratch --zone "$ZONE"
    gcloud compute -q instances set-disk-auto-delete ${instance} \
	--auto-delete --disk "$SCRATCH_DSK" --zone "$ZONE" &
fi

if ! test -e $CREATED_SCRATCH_DEV
then
    logger -s "Couldn't create or find the scratch disk!"
    exit 1
fi

if test -f "/run/do_blktests" ; then
    exit 0
fi

if ! vgs xt >& /dev/null
then
    pvcreate $CREATED_SCRATCH_DEV
    vgcreate xt $CREATED_SCRATCH_DEV

    if [ "$VDB_SIZE" != '0g' ]
    then
	lvcreate -L "${VDB_SIZE:-5g}"  -n vdb xt
	mke2fs -t ext4 -q /dev/mapper/xt-vdb
    fi
    if [ "$VDC_SIZE" != '0g' ]
    then
	lvcreate -L "${VDC_SIZE:-5g}"  -n vdc xt
    fi
    if [ "$VDD_SIZE" != '0g' ]
    then
	lvcreate -L "${VDD_SIZE:-5g}"  -n vdd xt
    fi
    if [ "$VDE_SIZE" != '0g' ]
    then
	lvcreate -L "${VDE_SIZE:-20g}"  -n vde xt
    fi
    if [ "$VDF_SIZE" != '0g' ]
    then
	lvcreate -L "${VDF_SIZE:-20g}"  -n vdf xt
    fi
fi
