#!/bin/bash
#
# gce-kexec -- this script handles switching to the kernel to be
# tested (using kexec), as well as those things that should be done as
# soon as possible (such as transferring the sendgrid password to a
# config file and erasing it)

. /usr/local/lib/gce-funcs

if ! test -f /etc/postfix/sasl_passwd
then
    sg_user=$(gce_attribute sg_user)
    sg_pass=$(gce_attribute sg_pass)
    if test -n "$sg_user" -a -n "$sg_pass"
    then
	echo "[smtp.sendgrid.net]:2525 $sg_user:$sg_pass" \
	     > /etc/postfix/sasl_passwd
	postmap /etc/postfix/sasl_passwd
	postfix reload
	gcloud compute instances -q remove-metadata ${instance} \
	       --keys sg_pass --zone "$ZONE"
    fi
fi

gcloud config set compute/zone $ZONE

if test -f /dev/disk/by-label/results
then
    e2fsck -fy /dev/disk/by-label/results
    mount /results
fi

if ! test -d /root/hooks
then
    mkdir -p /root/hooks
    hooks=$(gce_attribute hooks)
    if test -n "$hooks"
    then
	gsutil cp $hooks /run/hooks.tar.gz
	if test -f /run/hooks.tar.gz
	then
	    tar -C /root/hooks -xzf /run/hooks.tar.gz
	    rm /run/hooks.tar.gz
	fi
    fi
fi

kexec=$(gce_attribute kexec)
if test -z "$kexec" || grep -q fstestcfg /proc/cmdline; then exit 0; fi

if ! test -f /root/bzImage
then
    if ! gsutil cp $kexec /root/bzImage
    then
	logger "Couldn't find $kexec"
	exit 1
    fi
    sync
fi

kopt=$(gce_attribute kopt)
mem=$(gce_attribute mem)
cpus=$(gce_attribute nr_cpus)
mount_opts=$(gce_attribute mount_opts)
fstestcfg=$(gce_attribute fstestcfg)
fstestset=$(gce_attribute fstestset)
fstestexc=$(gce_attribute fstestexc)
fstestopt=$(gce_attribute fstestopt)
fstesttz=$(gce_attribute fstesttz)
fstesttyp=$(gce_attribute fstesttyp)
fstestapi=$(gce_attribute fstestapi)

if test -n "$fstesttz" -a -f /usr/share/zoneinfo/$fstesttz
then
    ln -sf /usr/share/zoneinfo/$fstesttz /etc/localtime
    echo $fstesttz > /etc/timezone
fi

if test -n "$mem"
then
    kopt="$kopt mem=${mem}M"
fi

if test -n "$cpus"
then
    kopt="$kopt maxcpus=$cpus"
fi

if test -n "$mount_opts"
then
    kopt="$kopt mount_opts=$mount_opts"
fi

run_hooks kexec
/usr/local/lib/gce-logger kexec to test kernel
systemctl stop rsyslog.service
sync
kexec /root/bzImage --command-line="root=/dev/sda1 ro console=ttyS0,38400n8 elevator=noop console=ttyS0 $kopt fstestcfg=$fstestcfg fstestset=$fstestset fstestexc=$fstestexc fstestopt=$fstestopt fstesttyp=$fstesttyp fstestapi=$fstestapi"
