#!/bin/bash

. /usr/local/lib/gce-funcs

run_hooks pre-setup

/usr/local/lib/gce-logger disk setup
gce_attribute orig_cmdline | base64 -d > /var/www/cmdline

/usr/local/lib/gce-add-metadata "kernel_version=$(uname -a)" &

script -c /usr/local/lib/gce-setup-results /var/log/gce-setup-results.log &
script -c /usr/local/lib/gce-setup-scratch /var/log/gce-setup-scratch.log &
if test -n "$NFSSRV" ; then
    script -c /usr/local/lib/gce-setup-nfs /var/log/gce-setup-nfs.log &
fi

cat > /var/www/varz <<EOF
kernel_version $(uname -a)
nr_cpus $(cat /proc/cpuinfo  | grep ^processor | tail -n 1 | awk '{print $3 + 1}')
total_mem $(grep MemTotal /proc/meminfo | awk '{print $2 / 1024}')
FSTESTCFG $FSTESTCFG
FSTESTSET $FSTESTSET
FSTESTOPT $FSTESTOPT
FSTESTTYP $FSTESTTYP
FSTESTAPI $FSTESTAPI
FSTESTEXC $FSTESTEXC
MNTOPTS $MNTOPTS
EOF

hostname > /var/www/hostname.inc
for i in diskstats meminfo lockdep lock_stat slabinfo vmstat
do
    chmod 444 "/proc/$i"
done
chmod 644 /var/log/messages /var/log/syslog /var/log/kern.log

kexec=$(gce_attribute kexec)

case "$kexec" in
    *-onetime)
	gsutil rm "$kexec" &
	;;
esac

tarmodules=$(gce_attribute tarmodules)

case "$tarmodules" in
    *-onetime)
	gsutil rm "$tarmodules" &
	;;
esac

wait

if test ! -f /results/setup-syslog
then
    cp /usr/local/lib/gce-syslog.conf /etc/rsyslog.d
    systemctl restart rsyslog.service
    dmesg >& /results/dmesg
    cp /var/log/syslog /results/setup-syslog
fi

for i in /usr/sbin/rsyslogd /usr/sbin/sshd
do
    pgrep -f $i | while read PID
    do
	echo -1000 > /proc/$PID/oom_score_adj
    done
done

run_hooks post-setup
